language: python

os: linux

branches:
  only:
    - master
#     - ^v[0-9]+\.[0-9]+[\.]?[a-c-]?[0-9]?[\w-]+\b

jobs:
  fast_finish: true
  include:
    # - env:
    #     - TOXENV=docs
    #     - READTHEDOCS=true
    #   name: "Documentation"
    #   python: 3.6
    #   addons:
    #     apt:
    #       packages:
    #         - pandoc
    - env: TOXENV=black
      name: "Black and flake8 compliance"
      python: 3.6
      addons:
        apt:
          packages:
            - libspatialindex-dev
    - env: TOXENV=py38
      name: "Python3.8 (Linux)"
      python: 3.8
      dist: xenial
      addons:
        apt:
          packages:
            - libspatialindex-dev
            - libnetcdf-dev
            - libhdf5-dev
    # - env:
    #     - TOXENV=py37-windows
    #     - PROJ_DIR=/c/OSGeo4W64
    #     - GDAL_VERSION=3.0.0
    #     - GDAL_DATA=/c/OSGeo4W64/share/gdal
    #   name: "Python3.7 (Windows)"
    #   os: windows
    #   language: shell
    #   before_install:
    #     - wget --directory-prefix=/c/temp/ https://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe
    #     - /c/temp/osgeo4w-setup-x86_64.exe -b -q -k -r -A -s http://download.osgeo.org/osgeo4w/ -a x86_64 -P proj,gdal,libspatialindex,geos
    #     - choco install python --version=3.7.5
    #     - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    #     - export PATH="/c/OSGeo4W64/include:/c/OSGeo4W64/bin:$PATH"
    #     - printenv
    #     - python -m pip install --upgrade pip wheel
    # - env: TOXENV=py37-macOS
    #   name: "Python3.7 (macOS)"
    #   os: osx
    #   language: shell
    #   addons:
    #     homebrew:
    #       update: true
    #       packages:
    #         - netcdf
    #         - spatialindex
    #   before_install:
    #     - printenv
    #     - brew link --overwrite python
    #     - python3 -m pip install --upgrade setuptools  # Disabled until homebrew updates python links
    #     - python3 -m pip install --upgrade pip  # Disabled until homebrew updates python links
    - env: TOXENV=py37
      name: "Python3.7 (Linux)"
      python: 3.7
      dist: xenial
      addons:
        apt:
          packages:
            - libspatialindex-dev
    - env: TOXENV=py36
      name: "Python3.6 (Linux)"
      python: 3.6
      addons:
        apt:
          packages:
            - libspatialindex-dev
    # - env: TOXENV=py36-xarray
    #   name: "Python3.6 (Linux + xarray@master + cftime@master)"
    #   python: 3.6
    #   addons:
    #     apt:
    #       packages:
    #         - libspatialindex-dev
    - env: TOXENV=py38-anaconda
      name: "Python3.8 (Linux + Anaconda)"
      python: 3.8
      before_install:
          - printenv
          - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          - bash miniconda.sh -b -p $HOME/miniconda
          - export PATH="$HOME/miniconda/bin:$PATH"
          - hash -r
          - conda config --set always_yes yes --set changeps1 no
          - conda install setuptools
          - conda update -q conda
          - conda create -n clisops -c conda-forge python=$TRAVIS_PYTHON_VERSION
          - source activate clisops
          - conda env update -f environment.yml
          - conda install pytest coveralls pytest-cov
      install:
          - conda install pip
          - pip install -e .
      script:
          - py.test --cov clisops
  allow_failures:
    - env: TOXENV=black
    - env: TOXENV=py38-anaconda
#    - env: TOXENV=py37-macOS
#    - env:
#      - TOXENV=py37-windows
#      - PROJ_DIR=/c/OSGeo4W64
#      - GDAL_VERSION=3.0.0
#      - GDAL_DATA=/c/OSGeo4W64/share/gdal
#    - env: TOXENV=py36-xarray

before_install:
    - printenv
    - pip install --upgrade pip

install:
    - pip install -U tox-travis

script: tox -e $TOXENV

# before_deploy:
#     - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
#
# deploy:
#   skip_existing: true
#   provider: pypi
#   distributions: sdist bdist_wheel
#   username: Zeitsperre
#   password:
#     secure: abc
#   on:
#     tags: true
#     all_branches: true
#     condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+[\.]?[a-c-]?[0-9]?[\w-]+\b
#     repo: Ouranosinc/clisops
#     python: 3.7
